f = open('MobNumber.txt','r')
line1=f.readline()
print("first mobile number",line1,end='')
line2=f.readline()
print("second mobile number",line2,end='')
line3=f.readline()
print("third mobile number",line1,end='')